# -*- coding: utf-8 -*-
"""predict_pet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Aeiu5UU7uMgBsWC5Z09fQpHirrUz8jWJ
"""

import tensorflow as tf
import numpy as np
from tensorflow.keras.preprocessing import image
import sys
import os

# Load model first
print("📦 Loading model...")
model = tf.keras.models.load_model("pet_face_classifier.h5")
print("✅ Model loaded.")

IMG_HEIGHT, IMG_WIDTH = model.input_shape[1], model.input_shape[2]
MODEL_PATH = 'pet_face_classifier.h5'

print("📦 Loading model...")
model = tf.keras.models.load_model(MODEL_PATH)
print("✅ Model loaded.")

def predict_pet(img_path):
    if not os.path.exists(img_path):
        print(f"❌ Image not found: {img_path}")
        return

    img = image.load_img(img_path, target_size=(IMG_HEIGHT, IMG_WIDTH))
    img_array = image.img_to_array(img)
    img_array = tf.expand_dims(img_array, 0)
    img_array = img_array / 255.0  # Normalized input

    prediction = model.predict(img_array)
    confidence = float(prediction[0][0])

    if confidence < 0.5:
        label = "🐱 Cat"
        confidence = 1 - confidence
    else:
        label = "🐶 Dog"

    print(f"{img_path} → {label} ({confidence:.2f} confidence)")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python predict_pet_mobilenet.py <image_path>")
    else:
        predict_pet(sys.argv[1])